version: '3'
networks:
  lkc-postgres:
    driver: bridge

services:
  postgres:
    image: postgres:17
    container_name: lkc-postgres-db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: citi
      POSTGRES_PASSWORD: r1dP75CHzWx0
      POSTGRES_DB: lkc
      POSTGRES_HOST_AUTH_METHOD: trust
    command: >
      postgres
      -c listen_addresses='*'
    ports:
      - '5432:5432'
    networks:
      - lkc-postgres